# **HyperParameter Tuning**

Proses pemilihan parameter Optimal



In [ ]:
from sklearn import svm, datasets
from sklearn.datasets import load_iris
from sklearn.model_selection import GridSearchCV
import pandas as pd

In [ ]:
iris = load_iris()

In [ ]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)

In [ ]:
model = svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(X_train,y_train)
model.score(X_test, y_test)
#0.9555555555555556

0.9555555555555556

In [13]:
from sklearn.model_selection import cross_val_score

In [14]:
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [15]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [16]:
cross_val_score(svm.SVC(kernel='rbf',C=20,gamma='auto'),iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

# **BAGAIMANA CARANYA MENCARI PARAMETER YANG TERBAIK TANPA HARUS SATU-SATU ??**

> USE HYPERPARAMETER TUNING



In [19]:
import numpy as np

kernels = ['linear', 'rbf']
C = [1,10,20]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval, C=cval, gamma='auto'), iris.data, iris.target, cv=5)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)

avg_scores

{'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668}



> **Masih tetap lama!**

Gunakan parameter Grid Search CV


In [20]:
from sklearn.model_selection import GridSearchCV

In [22]:
clf = GridSearchCV(svm.SVC(gamma='auto'), { #model dan parameter
    'C': [1,10,20],
    'kernel': ['rbf','linear']
}, cv=5, return_train_score=False
)

clf.fit(iris.data, iris.target)
clf.cv_results_ #dict of numpy(masked) ndarray

{'mean_fit_time': array([0.00502248, 0.00361047, 0.00172157, 0.00158248, 0.00155334,
        0.00123982]),
 'std_fit_time': array([2.75978259e-03, 4.58272444e-03, 3.93229261e-04, 2.24617007e-04,
        1.50829586e-04, 3.13120485e-05]),
 'mean_score_time': array([0.00131454, 0.00164008, 0.00393105, 0.00242639, 0.00095992,
        0.00085144]),
 'std_score_time': array([4.03403745e-04, 1.39475124e-03, 3.49344638e-03, 2.20459361e-03,
        6.38704462e-05, 3.01410122e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'ker

### *Rubah menjadi Data Frame*

In [23]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.005022      0.002760         0.001315        0.000403       1   
1       0.003610      0.004583         0.001640        0.001395       1   
2       0.001722      0.000393         0.003931        0.003493      10   
3       0.001582      0.000225         0.002426        0.002205      10   
4       0.001553      0.000151         0.000960        0.000064      20   
5       0.001240      0.000031         0.000851        0.000030      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [24]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [26]:
dir(clf) #explore

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 '

In [28]:
clf.best_score_

0.9800000000000001

In [29]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

Bagaimana jika kita mempunyai banyak data dan beberapa parameter (C nya pake range sampe 50) tentunya akan memproses dengan sangat lama



> Cara mengatasinya:



## **RandomizedSearchCV**

  tidak akan mencoba setiap permutasi dan kombinasi parameter, tetapi akan mencoba kombinasi acak dari nilai parameter

In [30]:
from sklearn.model_selection import RandomizedSearchCV

In [36]:
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
    'C': [1,10,20],
    'kernel': ['linear', 'rbf']
}, cv=5, return_train_score=False, n_iter=2) #n_iter berapa kombinasi ?

rs.fit(iris.data, iris.target)
rs.cv_results_
pd.DataFrame(rs.cv_results_)[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0      20          rbf         0.966667
1      20       linear         0.966667

BAGAIMANA JIKA DAA BEBERAPA MODEL PILIHAN ?


In [38]:
# prompt: import svm, randomforest, logisticregression

from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

#manakah yang memiliki kinerja terbaik ????

In [39]:
model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}

In [40]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })

In [41]:
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}

# **Exercise: Machine Learning Finding Optimal Model and Hyperparameters**

For digits dataset in sklearn.dataset, please try following classifiers and find out the one that gives best performance. Also find the optimal parameters for that classifier.


---

Untuk kumpulan data digit di sklearn.dataset, silakan coba mengikuti pengklasifikasi dan temukan yang memberikan kinerja terbaik. Temukan juga parameter optimal untuk pengklasifikasi tersebut.



```
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
```



In [48]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

In [42]:
from sklearn.datasets import load_digits
digits = load_digits()

In [46]:
digits.data


array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [47]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [54]:
model_params = {
    'rf' : {
        'model' : RandomForestClassifier(),
        'params' : {
            'n_estimators' : [1,5,10,20],
            # 'n_jobs' : [1,2,3]
        }
    },
    'lr': {
        'model' : LogisticRegression(),
        'params' : {
            'C' : [1,5,10,20]
        }
    },
    'gnb' : {
        'model' : GaussianNB(),
        'params' : {

        }
    },
    'mnb' : {
        'model' : MultinomialNB(),
        'params' : {

        }
    },
    'dtc' : {
        'model' : DecisionTreeClassifier(),
        'params' : {

        }
    }
}

In [56]:
scoress = []

for model_name, mp in model_params.items():
  clf = GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
  clf.fit(digits.data, digits.target)
  scoress.append({
      'model' : model_name,
      'best_score' : clf.best_score_,
      'best_params' : clf.best_params_
  })

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [57]:
df = pd.DataFrame(scoress,columns=['model','best_score','best_params'])
df

model  best_score           best_params
0    rf    0.913768  {'n_estimators': 20}
1    lr    0.913765              {'C': 1}
2   gnb    0.806928                    {}
3   mnb    0.870350                    {}
4   dtc    0.788573                    {}

# **Random Forest WIN!!**