In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
canada = pd.read_csv('canada_per_capita_income.csv')
canada.head()

year  per capita income (US$)
0  1970              3399.299037
1  1971              3768.297935
2  1972              4251.175484
3  1973              4804.463248
4  1974              5576.514583

In [ ]:
X = canada[['year']]
y = canada['per capita income (US$)']

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [ ]:
model.coef_

array([828.46507522])

In [ ]:
model.intercept_

-1632210.7578554575

In [ ]:
model.predict([[2020]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([41288.69409442])

# **Pickle**

1. keuntungan:
  1. Asli untuk Python
  1. Dapat membuat serial sebagian besar objek Python
  1. Penggunaan memori yang efisien dengan protokol=5

1. kekurangan :
  1. Pemuatan dapat mengeksekusi kode sembarangan
  1. Memerlukan lingkungan yang sama dengan lingkungan pelatihan



In [ ]:
import pickle

In [ ]:
with open('model_pickle', 'wb') as f: #write
  pickle.dump(model, f)  #menyimpan (men-serialisasi) objek Python ke dalam file

In [ ]:
with open('model_pickle', 'rb') as f: #read
  mp = pickle.load(f) #memanggil model

In [ ]:
mp.predict([[2020]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([41288.69409442])

# **JOBLIB**

1. Kelebihan
  1. Penggunaan memori yang efisien
  1. Mendukung pemetaan Memori
  1. Pintasan mudah untuk kompresi dan dekompresi

1. Kekurangan
  1. Format berbasis Pickle
  1. Pemuatan dapat mengeksekusi kode sembarangan
  1. Memerlukan lingkungan yang sama dengan lingkungan pelatihan

In [ ]:
!pip install joblib

In [ ]:
import joblib

In [20]:
joblib.dump(model, 'model_joblib') #('model dibuat', 'nama file')
#save model

['model_joblib']

In [21]:
mj = joblib.load('model_joblib') #load model

In [23]:
mj.predict([[2020]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([41288.69409442])

In [24]:
mj.coef_

array([828.46507522])